/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStrataForgeAdmin,
  IStrataForgeAdminInterface,
} from "../../contracts/IStrataForgeAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "index",
        type: "uint8",
      },
    ],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "adminCount",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "featureFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "featureCount",
        type: "uint8",
      },
    ],
    name: "payForFeatures",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IStrataForgeAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IStrataForgeAdminInterface {
    return new Interface(_abi) as IStrataForgeAdminInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStrataForgeAdmin {
    return new Contract(address, _abi, runner) as unknown as IStrataForgeAdmin;
  }
}
